version: "3"

services:

  polymath:
    container_name: polymath
    build: .
    command: python -u run
    restart: always
    ports:
      - 8088:8080
    volumes:
      - ./_docker/polymath:/polymath/polymath/storage

volumes:
  ssl_data:
